package extendscript.illustrator;

/* The compatibility type. */
@:native("Compatibility") extern enum Compatibility {

	ILLUSTRATOR3; 
	JAPANESEVERSION3; 
	ILLUSTRATOR8; 
	ILLUSTRATOR9; 
	ILLUSTRATOR10; 
	ILLUSTRATOR11; 
	ILLUSTRATOR12; 
	ILLUSTRATOR13; 
	ILLUSTRATOR14; 
	ILLUSTRATOR15; 
	ILLUSTRATOR16; 
	ILLUSTRATOR17; 
	ILLUSTRATOR19; 
	ILLUSTRATOR24; 

}